// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Miara",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Miara",
            targets: ["AppModule"],
            bundleIdentifier: "app.miara.miara",
            teamIdentifier: "JCUM8TD6Y4",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ]
        )
    ],
    dependencies: [
        .package(url: "../swiftui-introspect", "1.1.3"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftUIIntrospect", package: "swiftui-introspect")
            ],
            path: ".",
            resources: [
                .process("Tiles")
            ]
        )
    ]
)
